### ISSUE TITLE
single click can change the current song

### ISSUE THREAD

**Issue by ghost** [kekyo/PlayPcmWin#1]
hello, I think it would be nice if, instead of a single click being capable of changing the current song, it would only change on a double-click.

**Comment by kekyo** [comment]
@cyberhardt Thanks, this repository is something I imported from https://sourceforge.net/p/playpcmwin/wiki/PlayPcmWinEn/ to research WASAPI. (I have only really looked at the source code and have never made it work ;)

If you are interested, I suggest you refer to the original repository.
The Wiki is an email address at the end to contact the author.

**Comment by ghost** [comment]
ah, ok, I was aware of the sourceforge repository, but I thought you were the developer
